//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pripada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pripada()
        {
            this.Porucujes = new HashSet<Porucuje>();
        }
    
        public int Kvar_Sifra_kvara { get; set; }
        public int Auto_Sifra_auta { get; set; }
    
        public virtual Auto Auto { get; set; }
        public virtual Kvar Kvar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Porucuje> Porucujes { get; set; }
    }
}
