//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Radnik()
        {
            this.Uslugas = new HashSet<Usluga>();
        }
    
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string MBR { get; set; }
        public int Sifra_radnika { get; set; }
        public string Majstor { get; set; }
    
        public virtual Komercijalista Komercijalista { get; set; }
        public virtual Majstor Majstor1 { get; set; }
        public virtual Radnik_na_tehnickom_pregledu Radnik_na_tehnickom_pregledu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usluga> Uslugas { get; set; }
    }
}
