//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.AutoServisModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities3 : DbContext
    {
        public Entities3()
            : base("name=Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alat> Alats { get; set; }
        public virtual DbSet<Auto> Autoes { get; set; }
        public virtual DbSet<Deo> Deos { get; set; }
        public virtual DbSet<Dobavljac> Dobavljacs { get; set; }
        public virtual DbSet<Komercijalista> Komercijalistas { get; set; }
        public virtual DbSet<Kvar> Kvars { get; set; }
        public virtual DbSet<Majstor> Majstors { get; set; }
        public virtual DbSet<Popravka> Popravkas { get; set; }
        public virtual DbSet<Popravlja> Popravljas { get; set; }
        public virtual DbSet<Porucuje> Porucujes { get; set; }
        public virtual DbSet<Pripada> Pripadas { get; set; }
        public virtual DbSet<Radnik> Radniks { get; set; }
        public virtual DbSet<Radnik_na_tehnickom_pregledu> Radnik_na_tehnickom_pregledu { get; set; }
        public virtual DbSet<Tehnicki_pregled> Tehnicki_pregled { get; set; }
        public virtual DbSet<Usluga> Uslugas { get; set; }
    }
}
