//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Majstor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Majstor()
        {
            this.Popravljas = new HashSet<Popravlja>();
            this.Popravkas = new HashSet<Popravka>();
        }
    
        public string Specijalnost { get; set; }
        public int Sifra_radnika { get; set; }
    
        public virtual Radnik Radnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Popravlja> Popravljas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Popravka> Popravkas { get; set; }
    }
}
